services:

  lightcrm.api:
    image: ${DOCKER_REGISTRY-}lightcrmapi
    build:
      context: .
      dockerfile: LightCRM.API/Dockerfile
    depends_on: 
        - lightcrmdb
    environment:
        - ConnectionStrings__DefaultConnection=Host=localhost;Database=lightcrm;Username=postgres;Password=postgres
        - ASPNETCORE_ENVIRONMENT=Production

  lightcrmdb:
     image: postgres
     restart: always
     environment:
        POSTGRES_DB: lightcrm
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
     ports:
        -  5432:5432
     volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
     
