services:

  lightcrm.api:
    image: ${DOCKER_REGISTRY-}lightcrmapi
    build:
      context: .
      dockerfile: LightCRM.API/Dockerfile
    depends_on: 
        - lightcrmdb
    environment:
        - ASPNETCORE_URLS=http://+:80;
        - ConnectionStrings__Default=Host=lightcrmdb;Database=lightcrm;Username=postgres;Password=postgres
        - ASPNETCORE_ENVIRONMENT=Production
        - Jwt__SigningKey=${JWT_SIGNINGKEY}
        - Jwt__RefreshTokenExpiresIn=${JWT_REFRESHTOKENEXPIRESIN}
        - Jwt__AccessTokenExpiresIn=${JWT_ACCESSTOKENEXPIRESIN}
        - Jwt__Issuer=${JWT_ISSUER}
        - Jwt__Audience=${JWT_AUDIENCE}
        - Api__AdminPassword=${API_ADMINPASSWORD}
        - Api__AdminEmail=${API_ADMINEMAIL}
    ports:
      - "1001:80"

  lightcrmdb:
     image: postgres
     restart: always
     environment:
        POSTGRES_DB: lightcrm
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
     ports:
        -  5432:5432
     volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
     
